FROM node:20-alpine

WORKDIR /app/platform/common
COPY platform/common/ ./
RUN npm install

WORKDIR /app/gateway
COPY gateway/package.json ./
RUN npm install
COPY gateway/src ./src
COPY openapi ./openapi

ENV NODE_PATH=/app/platform/common/node_modules

EXPOSE 8080

RUN apk del curl wget netcat-openbsd ping nmap apk-tools 2>/dev/null || true; rm -rf /var/cache/apk/*

RUN addgroup -S ctf && adduser -S -G ctf ctfuser && chown -R ctfuser:ctf /app

USER ctfuser

CMD ["node", "src/index.js"]
