FROM node:20-slim

RUN apt-get update -y && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app/platform/db
COPY platform/db/ ./
RUN npm install && npx prisma generate

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN apt-get remove -y curl wget netcat-openbsd dnsutils iputils-ping nmap 2>/dev/null || true; rm -rf /var/lib/apt/lists/*

RUN groupadd -r ctf && useradd -r -g ctf ctfuser && chown -R ctfuser:ctf /app

USER ctfuser

ENTRYPOINT ["/entrypoint.sh"]
CMD ["sh", "-c", "npx prisma db push && node seed.js"]
